// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    save: function(name, pwd, callback) {
      if (callback === null) {
        callback = pwd;
        return callback(new Error("missing parameters"));
      } else {
        return callback();
      }
    },
    get: function(name, callback) {
      return callback();
    }
  };

}).call(this);
